### ISSUE TITLE
Linux启动报错

### ISSUE THREAD

**Issue by wolking** [3xxx/engineercms#25]
错误：
```
[ORM]2019/07/29 11:38:47  -[Queries/default] - [  OK /    db.Query /     0.0ms] - [SELECT T0.`id` FROM `user` T0 WHERE T0.`username` = ? LIMIT 1] - `admin`
2019/07/29 11:38:47 <nil>
2019/07/29 11:38:47.697 [E] [template.go:176]  parse template err: index_user.tpl template: index_user.tpl:35: function "subsuffix" not defined
panic: template: index_user.tpl:35: function "subsuffix" not defined

goroutine 1 [running]:
github.com/astaxie/beego.initBeforeHTTPRun()
	/root/gocode/src/github.com/astaxie/beego/beego.go:104 +0x215
github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
	/root/gocode/src/github.com/astaxie/beego/beego.go:58 +0x26
main.main()
	/root/gocode/src/github.com/3xxx/engineercms/main.go:29 +0xfc
```

**Comment by 3xxx** [comment]
这个功能是我前几天刚加入的，难道没有上传完整么？
