### ISSUE TITLE
咨询，201910版，linux运行出错

### ISSUE THREAD

**Issue by dawnxm** [3xxx/engineercms#35]
错误提示如下：
`
2020/02/05 09:58:38.686657 log_util.go:25: [Model:]
2020/02/05 09:58:38.686700 log_util.go:32: g.g: _, _
2020/02/05 09:58:38.686751 log_util.go:32: r.r: sub, obj, act, suf
2020/02/05 09:58:38.686765 log_util.go:32: p.p: sub, obj, act, suf
2020/02/05 09:58:38.686776 log_util.go:32: e.e: some(where (p_eft == allow))
2020/02/05 09:58:38.686787 log_util.go:32: m.m: g(r_sub, p_sub) && keyMatch(r_obj, p_obj) && regexMatch(r_suf, p_suf) && r_act == p_act
2020/02/05 09:58:38.687368 log_util.go:25: [Policy:]
2020/02/05 09:58:38.687440 log_util.go:25: [p :  sub, obj, act, suf :  [[2 /25001/25005/* POST .*] [2 /25001/25005/* PUT .*] [2 /25001/25005/* DELETE .*] [2 /25001/25005/* GET .*] [2 /25001/25005/* GET (?i:PDF)] [1 /25001/* POST .*] [1 /25001/* PUT .*] [1 /25001/* DELETE .*] [1 /25001/* GET .*] [1 /25001/25003/* GET (?i:PDF)] [1 /25001/25002/25013/* GET (?i:PDF)] [1 /25001/25002/25012/* GET (?i:PDF)] [1 /25001/25002/25011/* GET (?i:PDF)] [1 /25001/* GET (?i:PDF)] [2 /25001/25002/25013/* POST .*] [2 /25001/25002/25013/* PUT .*] [2 /25001/25002/25013/* DELETE .*] [2 /25001/25002/25013/* GET (?i:pdf)] [1 /25001/25004/* POST .*] [1 /onlyoffice/9 3 .*] [2 /onlyoffice/9 3 .*] [3 /onlyoffice/9 3 .*] [role_1 /onlyoffice/9 1 .*] [role_2 /onlyoffice/9 1 .*] [1 /onlyoffice/26 1 .*] [9 /onlyoffice/26 3 .*] [role_1 /26159/* POST .*] [role_1 /26159/* PUT .*] [role_1 /26159/* DELETE .*] [role_1 /26159/* GET (?i:PDF)] [role_1 /26197/* POST .*] [role_1 /26197/* PUT .*] [role_1 /26197/* DELETE .*] [role_1 /26197/* GET (?i:PDF)] [1 /onlyoffice/100 3 .*] [9 /onlyoffice/96 4 .*]]]
2020/02/05 09:58:38.687466 log_util.go:25: [g :  _, _ :  [[12 1] [87 2] [1 role_1] [9 role_1] [9 role_3]]]
2020/02/05 09:58:38.687489 log_util.go:25: [Role links for: g]
2020/02/05 09:58:38.687504 log_util.go:25: [9 < role_1, role_3]
2020/02/05 09:58:38.687516 log_util.go:25: [role_3 < ]
2020/02/05 09:58:38.687520 log_util.go:25: [12 < 1]
2020/02/05 09:58:38.687535 log_util.go:25: [1 < role_1]
2020/02/05 09:58:38.687543 log_util.go:25: [87 < 2]
2020/02/05 09:58:38.687573 log_util.go:25: [2 < ]
2020/02/05 09:58:38.687579 log_util.go:25: [role_1 < ]
2020/02/05 09:58:38.688099 log_util.go:25: [Policy:]
2020/02/05 09:58:38.688173 log_util.go:25: [p :  sub, obj, act, suf :  [[2 /25001/25005/* POST .*] [2 /25001/25005/* PUT .*] [2 /25001/25005/* DELETE .*] [2 /25001/25005/* GET .*] [2 /25001/25005/* GET (?i:PDF)] [1 /25001/* POST .*] [1 /25001/* PUT .*] [1 /25001/* DELETE .*] [1 /25001/* GET .*] [1 /25001/25003/* GET (?i:PDF)] [1 /25001/25002/25013/* GET (?i:PDF)] [1 /25001/25002/25012/* GET (?i:PDF)] [1 /25001/25002/25011/* GET (?i:PDF)] [1 /25001/* GET (?i:PDF)] [2 /25001/25002/25013/* POST .*] [2 /25001/25002/25013/* PUT .*] [2 /25001/25002/25013/* DELETE .*] [2 /25001/25002/25013/* GET (?i:pdf)] [1 /25001/25004/* POST .*] [1 /onlyoffice/9 3 .*] [2 /onlyoffice/9 3 .*] [3 /onlyoffice/9 3 .*] [role_1 /onlyoffice/9 1 .*] [role_2 /onlyoffice/9 1 .*] [1 /onlyoffice/26 1 .*] [9 /onlyoffice/26 3 .*] [role_1 /26159/* POST .*] [role_1 /26159/* PUT .*] [role_1 /26159/* DELETE .*] [role_1 /26159/* GET (?i:PDF)] [role_1 /26197/* POST .*] [role_1 /26197/* PUT .*] [role_1 /26197/* DELETE .*] [role_1 /26197/* GET (?i:PDF)] [1 /onlyoffice/100 3 .*] [9 /onlyoffice/96 4 .*]]]
2020/02/05 09:58:38.688196 log_util.go:25: [g :  _, _ :  [[12 1] [87 2] [1 role_1] [9 role_1] [9 role_3]]]
2020/02/05 09:58:38.688228 log_util.go:25: [Role links for: g]
2020/02/05 09:58:38.688242 log_util.go:25: [role_1 < ]
2020/02/05 09:58:38.688248 log_util.go:25: [9 < role_1, role_3]
2020/02/05 09:58:38.688253 log_util.go:25: [role_3 < ]
2020/02/05 09:58:38.688257 log_util.go:25: [12 < 1]
2020/02/05 09:58:38.688272 log_util.go:25: [1 < role_1]
2020/02/05 09:58:38.688285 log_util.go:25: [87 < 2]
2020/02/05 09:58:38.688296 log_util.go:25: [2 < ]
panic: you are in dev mode. So please set gopath

goroutine 1 [running]:
github.com/astaxie/beego.(*ControllerRegister).Include(0xc0000d5a20, 0xc00041b340, 0x2, 0x2)
        /root/gocode/src/github.com/astaxie/beego/router.go:258 +0x9d1
github.com/astaxie/beego.(*Namespace).Include(0xc00041b4a0, 0xc00041b340, 0x2, 0x2, 0xc00041b4a0)
        /root/gocode/src/github.com/astaxie/beego/namespace.go:186 +0x4d
github.com/astaxie/beego.NSInclude.func1(0xc00041b4a0)
        /root/gocode/src/github.com/astaxie/beego/namespace.go:302 +0x46
github.com/astaxie/beego.NewNamespace(0x14ceb03, 0x6, 0xc0000951f8, 0x1, 0x1, 0xc000430201)
        /root/gocode/src/github.com/astaxie/beego/namespace.go:42 +0x87
github.com/astaxie/beego.NSNamespace.func1(0xc00041b480)
        /root/gocode/src/github.com/astaxie/beego/namespace.go:386 +0x52
github.com/astaxie/beego.NewNamespace(0x14ca846, 0x3, 0xc000439f28, 0x8, 0x8, 0xc000430240)
        /root/gocode/src/github.com/astaxie/beego/namespace.go:42 +0x87
github.com/3xxx/engineercms/routers.init.1()
        /root/gocode/src/github.com/3xxx/engineercms/routers/router.go:114 +0xc18
`

**Comment by 3xxx** [comment]
你是不是没有放到包里去啊？

**Comment by dawnxm** [comment]
放在包里面运行。和那个exe可执行文件是同目录的。&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "hotqin888"; 
Date: 2020年2月5日(星期三) 晚上6:03
To: "3xxx/engineercms"; 
Cc: "光头大师"; "Author"; 
Subject: Re: [3xxx/engineercms] 咨询，201910版，linux运行出错 (#35)

&nbsp;

你是不是没有放到包里去啊？

**Comment by 3xxx** [comment]
conf文件夹下的app.conf里的runmode=prod

**Comment by dawnxm** [comment]
修改了以后确实能跑起来了。不加后台运行的话，程序一直在输出运行反馈。

**Comment by 3xxx** [comment]
可能我在main函数里没有将debug关闭。

**Comment by dawnxm** [comment]
可以在conf中配置一个开关参数，来设置debug信息的显示。

**Comment by 3xxx** [comment]
哦哦，就是，好主意。
